services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb

networks:
  default:
    driver: bridge
    name: roboshop
    external: false # set to true if you created the network manually using `docker network create`

